### ISSUE TITLE
Converters

### ISSUE THREAD

**Issue by vineey** [vineey/archelix-rsql#2]
Implements converters from rsql-parser to Querydsl sets of Path types such as DatePath, DateTimePath, StringPath, EnumPath, NumberPath, BooleanPath,  CollectionPath, TimePath,etc.

**Comment by vineey** [comment]
With regards to known Path types, we just have missing converters for  the following Paths:
- CollectionPath
- SetPath
- ListPath

**Comment by vineey** [comment]
Completed basic support for CollectionPathBase common to all three paths stated above with custom operators size equal and size not equal.

**Comment by ghost** [comment]
A great way to query a collection path like "List `<AnotherModel>` details" is using any() method of querydsl's ListPath.

In Java:
Map<String, Path> pathHashMap = ImmutableMap.<String, Path>builder()
                .put("employee.details.any.name", QEmployee.employee.details.any().name).build();

In Rsql:
employee.details.any.name==somename

Generic path map code:
```java
	private Map<String, Path> prepareFieldMap(Path<?> path, Map<String, Path> pathMapping, String prefix,
			int additionalLevels) {
		for (Field fld : path.getClass().getFields()) {
			if (Modifier.isPublic(fld.getModifiers()) && !Modifier.isStatic(fld.getModifiers())
					&& Path.class.isAssignableFrom(fld.getType())) {
				try {
					pathMapping.put(prefix + fld.getName(), (Path<?>) fld.get(path));
					if (CollectionPathBase.class.isAssignableFrom(fld.getType())) {
						Path<?> any = (Path<?>) ((CollectionPathBase<?, ?, ?>) fld.get(path)).any();
						pathMapping.put(prefix + fld.getName() + ".any", any);
						if (additionalLevels >= 0) {
							prepareFieldMap(any, pathMapping, prefix + fld.getName() + ".any" + ".",
									additionalLevels - 1);
						}
					} else if (additionalLevels > 0 && fld.getType().getSimpleName().startsWith("Q")) {
						prepareFieldMap((Path<?>) fld.get(path), pathMapping, prefix + fld.getName() + ".",
								additionalLevels - 1);
					}
				} catch (IllegalArgumentException | IllegalAccessException e) {
					e.printStackTrace();
				}
			}
		}
		return pathMapping;
	}
```
